spring.application.name=app-redis-springboot
# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3309/redis_springboot
spring.datasource.username=root
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Tiempo de vida de la caché
spring.cache.redis.time-to-live=600000